
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  db: ${REDIS_DB}

postgres:
  connection:
    host: ${DB_HOST}
    port: ${DB_PORT}
    db: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: ktmanager-${IMAGE_VERSION}.log
